baseURL = "/"
languageCode = "en"
title = "Samoyed Time"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
enableEmoji = true

# Ignore naughty files
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Google Analytics UA number
googleAnalytics = "UA-2333333-4"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "SamoyedTime"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "Samoyed Time"
  subtitle = "~ Samoyed Dog Breed Information ~"
  description = "Originally bred to hunt, haul sledges, and herd reindeer, the Samoyed dog breed proved a valuable companion for northwestern Siberia’s Samoyede people.."
  paginate = 10

  # Choose your social networks
  email = "pedram.navid@gmail.com"
  github = "pedramnavid"
  twitter = "helloitspedr"
  linkedin = "pedramnavid"

[permalinks]
    post = "/:year/:month/:day/:slug/"
